[package]
name = "bevy_simplenet"
description = "Simple server/client channel implemented over websockets with support for Bevy"
authors = ["koe <ukoe@protonmail.com>"]
version = "0.1.1"
edition = "2021"
keywords = ["gamedev", "networking"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/UkoeHB/bevy_simplenet"

[dependencies]
async-trait = { version = "0.1.71" }
bevy        = { version = "0.10.1", default-features = false }
bincode     = { version = "1.3.3" }
crossbeam   = { version = "0.8.2" }
ezsockets   = { git = "https://github.com/UkoeHB/ezsockets.git", branch = "socket_close", features = [ "tungstenite" ] }
futures     = { version = "0.3.0" }
serde       = { version = "1.0.160" }
serde_json  = { version = "1.0.100" }
serde_with  = { version = "3.0.0" }
tokio       = { version = "1.29.1", features = [ "rt-multi-thread" ] }
tracing     = { version = "0.1.32" }
url         = { version = "2.4.0" }

[dev-dependencies]
tracing-subscriber = { version = "0.3.9" }
