[package]
name = "bevy_simplenet-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy                  = { version = "0.11",  default_features = false }
bevy_kot              = { version = "0.0.5" }
bevy_simplenet        = { path = "../../", default_features = false, features = [ "server", "bevy" ] }
bevy_simplenet-common = { path = "../common/" }
enfync                = { version = "0.1" }
